# -*- coding: utf-8 -*-
"""Smart_expense_tracker.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHliTyuersPpMdvqyUQzld0olikSmZk2
"""

import json
import pandas as pd
import matplotlib.pyplot as plt

print("Smart Expense Tracker")
class ExpenseTracker:

    def __init__(self):
        self.expenses = {}
        self.load_expenses()

    # ------------------------------
    # Load Previous Data
    # ------------------------------
    def load_expenses(self):
        try:
            with open("expenses.json", "r") as f:
                self.expenses = json.load(f)
            print("📂 Loaded previous expenses.")
        except FileNotFoundError:
            print("📁 No previous data. Starting fresh.")

    # ------------------------------
    # Save Data to JSON
    # ------------------------------
    def save_expenses(self):
        with open("expenses.json", "w") as f:
            json.dump(self.expenses, f)
        print("💾 Expenses saved!")

    # ------------------------------
    # Add Expense
    # ------------------------------
    def add_expense(self):
        category = input("Enter category: ")
        amount = float(input("Enter amount: "))
        self.expenses[category] = self.expenses.get(category, 0) + amount
        print("✔ Expense Added!")

    # ------------------------------
    # View All Expenses
    # ------------------------------
    def view_expenses(self):
        if not self.expenses:
            print("⚠ No expenses found.")
            return

        print("\n📋 Your Expenses:")
        for cat, amt in self.expenses.items():
            print(f"{cat}: ₹{amt}")
        print("Total =", sum(self.expenses.values()))

    # ------------------------------
    # Clear All Expenses
    # ------------------------------
    def clear_expenses(self):
        confirm = input("Are you sure? (yes/no): ").lower()
        if confirm == "yes":
            self.expenses.clear()
            print("🧹 All cleared!")
        else:
            print("❌ Cancelled.")

    # ------------------------------
    # Summary Report
    # ------------------------------
    def show_summary(self):
        if not self.expenses:
            print("⚠ No expenses!")
            return

        total = sum(self.expenses.values())
        highest = max(self.expenses, key=self.expenses.get)
        lowest = min(self.expenses, key=self.expenses.get)

        print("\n📊 Summary Report:")
        print("💰 Total:", total)
        print("🔼 Highest:", highest, "₹", self.expenses[highest])
        print("🔽 Lowest:", lowest, "₹", self.expenses[lowest])

    # ------------------------------
    # Sort Expenses
    # ------------------------------
    def sort_expenses(self):
        if not self.expenses:
            print("⚠ No expenses to sort!")
            return

        print("\n1. Sort Low → High")
        print("2. Sort High → Low")

        choice = input("Choose option: ")

        if choice == "1":
            sorted_exp = sorted(self.expenses.items(), key=lambda x: x[1])
            print("\n🔽 Sorted (Low → High):")
        elif choice == "2":
            sorted_exp = sorted(self.expenses.items(), key=lambda x: x[1], reverse=True)
            print("\n🔼 Sorted (High → Low):")
        else:
            print("❌ Invalid option")
            return

        for cat, amt in sorted_exp:
            print(f"{cat}: ₹{amt}")

    # ------------------------------
    # Filter Expenses
    # ------------------------------
    def filter_expenses(self):
        if not self.expenses:
            print("⚠ No expenses to filter!")
            return

        limit = float(input("Show expenses greater than: ₹"))
        print(f"\n📌 Expenses greater than ₹{limit}:")

        found = False
        for cat, amt in self.expenses.items():
            if amt > limit:
                print(f"{cat}: ₹{amt}")
                found = True

        if not found:
            print("No expenses above this amount.")

    # ------------------------------
    # Export CSV (for graphs)
    # ------------------------------
    def export_data_for_visualization(self):
        if not self.expenses:
            print("⚠ No data available to export!")
            return

        df = pd.DataFrame(list(self.expenses.items()), columns=['Category', 'Amount'])
        df.to_csv("expenses_data.csv", index=False)
        print("📁 Data exported as expenses_data.csv")

    # ------------------------------
    # SHOW GRAPHS INSIDE PROJECT
    # ------------------------------
    def show_graphs(self):
        if not self.expenses:
            print("⚠ No data to display graphs!")
            return

        df = pd.DataFrame(list(self.expenses.items()), columns=['Category', 'Amount'])

        # BAR CHART
        plt.figure(figsize=(8, 5))
        plt.bar(df['Category'], df['Amount'])
        plt.title("Expenses by Category")
        plt.xlabel("Category")
        plt.ylabel("Amount (₹)")
        plt.show()

        # PIE CHART
        plt.figure(figsize=(6, 6))
        plt.pie(df['Amount'], labels=df['Category'], autopct='%1.1f%%')
        plt.title("Expense Distribution")
        plt.show()

        # LINE CHART
        plt.figure(figsize=(8, 5))
        plt.plot(df['Category'], df['Amount'], marker='o')
        plt.title("Expense Trend")
        plt.xlabel("Category")
        plt.ylabel("Amount (₹)")
        plt.show()

    # ------------------------------
    # MAIN MENU
    # ------------------------------
    def start(self):
        while True:
            print("\n===== Expense Tracker =====")
            print("1. Add Expense")
            print("2. View Expenses")
            print("3. Summary Report")
            print("4. Clear All")
            print("5. Save & Exit")
            print("6. Sort Expenses")
            print("7. Filter Expenses")
            print("8. Export to CSV")
            print("9. Visualize Expenses (Graphs)")

            choice = input("Enter choice: ")

            if choice == "1":
                self.add_expense()
            elif choice == "2":
                self.view_expenses()
            elif choice == "3":
                self.show_summary()
            elif choice == "4":
                self.clear_expenses()
            elif choice == "5":
                self.save_expenses()
                print("Bye! 👋")
                break
            elif choice == "6":
                self.sort_expenses()
            elif choice == "7":
                self.filter_expenses()
            elif choice == "8":
                self.export_data_for_visualization()
            elif choice == "9":
                self.show_graphs()
            else:
                print("❌ Invalid choice")


# ------------------------------
# START PROGRAM
# ------------------------------
if __name__ == "__main__":
    tracker = ExpenseTracker()
    tracker.start()